<?xml version="1.0" standalone="yes"?><!DOCTYPE authors [
<!ELEMENT authors (name)* >
<!ELEMENT name (firstname, lastname) >
<!ELEMENT firstname (#PCDATA) >
<!ELEMENT lastname (#PCDATA) >
]>
<authors>
    <name>
        <firstname>DO QUANG</firstname>
        <lastname>Khai</lastname>
    </name>
    <name>
        <firstname>Somebody</firstname>
        <lastname>ELse</lastname>
    </name>
</authors>