=== sptungG/WP.20212.Group10/lab11/9.1/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!DOCTYPE group [
<!ELEMENT group (student) *>
<!ELEMENT student (id ,name ,class)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT class (#PCDATA)>
]>

=== sptungG/WP.20212.Group10/lab11/9.1/studentInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE group SYSTEM "student.dtd">

<group>
    <student>
        <id> 20184312 </id>
        <name> Nguyễn Mạnh Tiến </name>
        <class> ICT.02 K63 </class>
    </student>

    <student>
        <id> 20184274 </id>
        <name> Đỗ Quang Khải </name>
        <class> ICT.01 K63 </class>
    </student>

    <student>
        <id> 20184326 </id>
        <name> Ngô Việt Tùng </name>
        <class> ICT.01 K63 </class>
    </student>
</group>
